 function arm_devicev5(dirname, filename_fits,k_adult_male,count,pathfunctions,pathbegdata,pathsavedata)

newFolder=strcat(pathbegdata,dirname);
genpath('newFolder');
cd(newFolder);
load(filename_fits);
newFolder=pathfunctions;
genpath('newFolder');
cd(newFolder);
for  i=1:1:length(k_adult_male)
j=k_adult_male(i,1);
 m=count+i;
newFolder=pathsavedata;
genpath('newFolder');
cd(newFolder);
namenew=strcat('specimen_#',num2str(m),'.h5');
fileID = H5F.open(namenew,'H5F_ACC_RDWR','H5P_DEFAULT');
newFolder='C:\Users\bfarrell\Documents\M files\OHC analysis\HDF5format\final functions';
genpath('newFolder');
cd(newFolder);
researcher=array_of_do_fits(1,j).researcher; % this is an attribute
dofexp=array_of_do_fits(1,j).dofexp; % this is an attribute
cellnumber=array_of_do_fits(1,j).cellnumber; % this is an attribute
datasteward='Brenda Farrell, PhD';% this is an attribute
group_id_ld = H5G.create(fileID, '/measurement device', 'H5P_DEFAULT', 'H5P_DEFAULT', 'H5P_DEFAULT');
%
didefinition= 'specialized instrumentation used';
dadefinition= char(didefinition);
ATTRIBUTE='definition';
write_attribute_for_group(group_id_ld,dadefinition,ATTRIBUTE);

% create datasets
patch_clamp_amplifier='Molecular Devices Axopatch 200B';
type = H5T.copy ('H5T_C_S1');
space=H5S.create('H5S_SCALAR');
name_def='patch_clamp_amplifier';
dataset_id=create_and_write_string_dataset(group_id_ld,space,type,name_def,patch_clamp_amplifier);

%%%%%%%%%%%%%add definition

attribute_general(dataset_id,researcher, dofexp, cellnumber, datasteward); % calls a function to add attributes

didefinition= 'A headstage connected to a box that houses additional electronics that is configured to clamp the current and measure voltage or clamp the voltage and measure current. In the studies the resistor-feedback mode of headstage was used to clamp the voltage, i.e., an operational amplifier in current-follower configuration'; 
dadefinition= char(didefinition);
ATTRIBUTE='definition';
specific_string_attribute(dataset_id,ATTRIBUTE,dadefinition);

% create datasets
camera='MTI-DAGE NC-70 Newvicon';
type = H5T.copy ('H5T_C_S1');
space=H5S.create('H5S_SCALAR');
name_def='camera';
dataset_id=create_and_write_string_dataset(group_id_ld,space,type,name_def,camera);

%%%%%%%%%%%%%add definition

attribute_general(dataset_id,researcher, dofexp, cellnumber, datasteward); % calls a function to add attributes

didefinition='An analog camera mounted to the microscope and connected with coaxial cable to a control box that sets gain and sensitivity. The video output is fed via BNC connector to monitor'; 
dadefinition= char(didefinition);
ATTRIBUTE='definition';
specific_string_attribute(dataset_id,ATTRIBUTE,dadefinition);
% create datasets
DAQ_card='National Instruments PCI-6052E';
type = H5T.copy ('H5T_C_S1');
space=H5S.create('H5S_SCALAR');
name_def='DAQ_card';
dataset_id=create_and_write_string_dataset(group_id_ld,space,type,name_def,DAQ_card);

%%%%%%%%%%%%%add definition

attribute_general(dataset_id,researcher, dofexp, cellnumber, datasteward); % calls a function to add attributes

didefinition='The digital acquisition card that generates the stimulus voltage that is fed to patch clamp amplifier and reads the current generated by the amplifier'; 
dadefinition= char(didefinition);
ATTRIBUTE='definition';
specific_string_attribute(dataset_id,ATTRIBUTE,dadefinition);

microscope='Zeiss Axiovert 135 TV';
type = H5T.copy ('H5T_C_S1');
space=H5S.create('H5S_SCALAR');
name_def='microscope';
dataset_id=create_and_write_string_dataset(group_id_ld,space,type,name_def,microscope);

%%%%%%%%%%%%%add definition

attribute_general(dataset_id,researcher, dofexp, cellnumber, datasteward); % calls a function to add attributes

didefinition='Inverted microscope used to view the cells and position the patch pipette for the assay'; 
dadefinition= char(didefinition);
ATTRIBUTE='definition';
specific_string_attribute(dataset_id,ATTRIBUTE,dadefinition);

pressure_clamp='HSPC-1 ALA Scientific Instruments';
type = H5T.copy ('H5T_C_S1');
space=H5S.create('H5S_SCALAR');
name_def='pressure_clamp';
dataset_id=create_and_write_string_dataset(group_id_ld,space,type,name_def,pressure_clamp);

%%%%%%%%%%%%%add definition

attribute_general(dataset_id,researcher, dofexp, cellnumber, datasteward); % calls a function to add attributes

didefinition='High speed pressure clamp used to control pipette pressure during the assay'; 
dadefinition= char(didefinition);
ATTRIBUTE='definition';
specific_string_attribute(dataset_id,ATTRIBUTE,dadefinition);

clearvars -except dirname filename_fits count k_adult_male array_of_do_fits pathfunctions pathbegdata pathsavedata;


end
end
%%
